---
- name: Test
  hosts: all
  roles:
    - role: geerlingguy.postgresql
      tags: postgresql-verylongverylongverylongverylongverylongverylongverylongverylongverylongverylongverylongverylongverylongverylongverylongverylongverylongverylong
